### ISSUE TITLE
Static analyzers

### ISSUE THREAD

**Issue by szepeviktor** [Brain-WP/Assets#1]
Hello @gmazzap !

Very nice code. Psalm helps you keep code quality high.

Some things to consider

- use phpstan-wordpress, you don't have to write [core functions stubs](https://github.com/GiacoCorsiglia/wordpress-stubs) yourself!
- @phpstan is a better tool
- near-zero configuration
- try avoiding casting values `$baseUrl = (string)$context->baseUrl();`
- convert closures to proper methods
- figure out null default values

All the best to you!

```diff
diff --git a/composer.json b/composer.json
index e8db817..a5f08e2 100644
--- a/composer.json
+++ b/composer.json
@@ -29,7 +29,8 @@
         "brain/monkey": "^2",
         "squizlabs/php_codesniffer": "3.2.*",
         "inpsyde/php-coding-standards": "0.*",
-        "vimeo/psalm": "^3"
+        "phpstan/phpstan-shim": "^0.11.8",
+        "szepeviktor/phpstan-wordpress": "^0.1.2"
     },
     "scripts": {
         "qa": [
diff --git a/src/Assets.php b/src/Assets.php
index d216df9..f8c8d88 100644
--- a/src/Assets.php
+++ b/src/Assets.php
@@ -810,7 +810,9 @@ class Assets
      */
     private function tryRelativeUrl(string $url, string $folder, ?string $baseUrl = null): string
     {
+        /** @var string[] */
         $urlData = parse_url($url);
+        /** @var string[] */
         $baseData = parse_url($baseUrl ?? $this->context->baseUrl());

         $urlHost = (string)($urlData['host'] ?? '');
diff --git a/src/UrlResolver/DirectUrlResolver.php b/src/UrlResolver/DirectUrlResolver.php
index 9275d2f..883d217 100644
--- a/src/UrlResolver/DirectUrlResolver.php
+++ b/src/UrlResolver/DirectUrlResolver.php
@@ -29,6 +29,7 @@ final class DirectUrlResolver implements UrlResolver
         $baseUrl = $this->context->baseUrl();
         $basePath = $this->context->basePath();

+        /** @var string[] */
         $urlData = parse_url($relative);
         $path = trim((string)($urlData['path'] ?? ''), '/');
         $query = (string)($urlData['query'] ?? '');
diff --git a/src/Version/LastModifiedVersion.php b/src/Version/LastModifiedVersion.php
index 564fe9b..b2e1e43 100644
--- a/src/Version/LastModifiedVersion.php
+++ b/src/Version/LastModifiedVersion.php
@@ -7,7 +7,7 @@ use Brain\Assets\Context\Context;
 final class LastModifiedVersion implements Version
 {
     /**
-     * @var array<string, array{0:string, 1:int}>
+     * @var array<string, array>
      */
     private $bases = [];
```

phpstan.neon.dist

```yaml
# Start command: vendor/bin/phpstan analyze

includes:
    - phar://phpstan.phar/conf/bleedingEdge.neon
    - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
    level: max
    paths:
        - %currentWorkingDirectory%/src/
    ignoreErrors:
        # Uses func_get_args()
        - '#^Function add_query_arg invoked with [123] parameters?, 0 required\.$#'
```
